# NOTE: update this with your service name
service: aws-nodejs-typescript-docker-template

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-provisioned-concurrency-autoscaling

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 4000
  bundle:
    tsConfig: "tsconfig.eslint.json"
    linting: false

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  timeout: 30
  role: arn:aws:iam::999110959427:role/lambda-labs-role

  environment:
    STAGE: ${env:STAGE}
    REGION: ${env:REGION}
    MY_SECRET: ${env:MY_SECRET}

functions:
  hello:
    handler: src/handler.hello
    provisionedConcurrency: 1
    concurrencyAutoscaling: true #all settings: https://www.serverless.com/plugins/serverless-provisioned-concurrency-autoscaling
    events:
      - http:
          path: hello
          method: get
